language: rust

dist: trusty
sudo: false

rust:
  - nightly

install:
  - rustup target add wasm32-unknown-unknown
  - cargo install cargo-web

env:
  - TARGET=wasm32-unknown-unknown

script:
  - cargo web build --target-webasm --release

before_deploy:
  - mkdir -p dist/js
  - cp src/static/index.html dist/
  - cp target/wasm32-unknown-unknown/release/explain-rs.js dist/js/app.js
  - cp target/wasm32-unknown-unknown/release/explain-rs.wasm dist/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: 'dist'
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
