[package]
authors = ["MSleepyPanda <m.sleepypanda@gmail.com>"]
name = "explain-rs-derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "0.3.12"

[dependencies.syn]
version = "0.11.10"
features = ["parsing"]